### ISSUE TITLE
golang wasi file create not working

### ISSUE THREAD

**Issue by izouxv** [pgavlin/warp#1]
func main() {
	f, err := os.Create("input.txt")
	if err != nil {
		println(err)
		return
	}
	defer f.Close()
	f.Write([]byte("hello world\n"))
}

**Comment by izouxv** [comment]
[testgo.zip](https://github.com/pgavlin/warp/files/6603524/testgo.zip)

**Comment by pgavlin** [comment]
Thank you for the excellent repro! I'm sorry it's taken me so long to get around to looking at this--I set the project aside for a while.

I think that the issue here is the way the preopen is mapped. If I make the following edit, the test passes:

```diff
--- warp_test.orig.go   2021-12-12 16:56:18.000000000 -0800
+++ warp_test.go        2021-12-12 16:56:24.000000000 -0800
@@ -61,7 +61,7 @@
        err = wasi.Run("", def, &wasi.RunOptions{
                Options: &wasi.Options{
                        Preopen: []wasi.Preopen{
-                               {FSPath: dir, Path: dir, Rights: wasi.AllRights, Inherit: wasi.AllRights},
+                               {FSPath: dir, Path: ".", Rights: wasi.AllRights, Inherit: wasi.AllRights},
                        },
                },
        })
```

The documentation here is sorely lacking (improving it is on my list of TODOs for this project). The `FSPath` property is the path of the mapped file on the host; the `Path` property is the path of the mapping on the target. Using the same value for `FSPath` and `Path` would require all paths accessed by the target to be under that path. Adding a mapping with `Path: "."` ensures that the target module can access its own working directory.
